apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: excercise 1 b

on:
  workflow_dispatch:
    inputs:
      firstname:
        type: string
        default: Lovely
        required: true


jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world ${{inputs.firstname}}"
